jobs:
  include:
  - stage: test
    language: python
    python: '2.7'
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libexempi3-32bit
    install:
    - pip install codecov
    - python setup.py install
    - pip install -e .[dev]
    script: dispatch-admin coverage
    after_success: codecov
  - language: node_js
    node_js: 6.9.5
    install:
    - cd dispatch/static/manager
    - yarn setup
    script: yarn build
  - stage: deploy
    language: python
    python: '2.7'
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libexempi3-32bit
    - nvm install 6.9.5
    - nvm use 6.9.5
    install:
    - cd dispatch/static/manager
    - yarn setup
    - yarn build
    - cd ../../../
    script: python setup.py sdist
    deploy:
      provider: pypi
      user: ubyssey
      skip_cleanup: true
      password:
        secure: BQQSSY2KmBG4Yq8BoDIh2vHqiftXjiogU1mH6gq1fuwaAfhMnNzXK+BKnS/fqIc24cNYoFEsnH4UYQVqyDqKr/ammYBJX2+zfQtf2JqrdYaxQWZ0Fxcu7FqiWmX43nukJy7R4Yg746DJkQL15zWuk1yAzbrD+IQPzmNddFXyBF0=
      on:
        tags: true
